name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: the-coding-owl/action-typo3-extension-repository-upload@0.0.1
        env:
          SECRET_USERNAME: ${{ secrets.USERNAME }}
          SECRET_PASSWORD: ${{ secrets.PASSWORD }}
          EXTENSION_KEY: 'solradmin'
          UPLOAD_MESSAGE: 'Automatic release built from GitHub, see the https://github.com/Apen/solradmin/ for details.'